"""API endpoints for the order fulfilment workflow.

Separated from the app factory so the route logic is easy to read
and test independently.
"""

from __future__ import annotations

import asyncio
import logging
import uuid
from datetime import UTC, datetime
from typing import Any

from examples.order_fulfilment.schemas import (
    CreateOrderRequest,
    OrderStatusResponse,
    PaymentWebhookPayload,
    StepView,
)

logger = logging.getLogger("workchain.example.app")


def register_routes(app: Any, get_store, get_runner, get_workflow) -> None:
    """
    Attach order fulfilment routes to a FastAPI app.

    Parameters
    ----------
    app:
        FastAPI application instance.
    get_store:
        Callable returning the current ``MongoWorkflowStore``.
    get_runner:
        Callable returning the current ``WorkflowRunner``.
    get_workflow:
        Callable returning the ``Workflow`` blueprint.
    """
    from fastapi import HTTPException

    @app.post("/orders", status_code=201)
    async def create_order(request: CreateOrderRequest) -> dict[str, Any]:
        """
        Create an order and start the fulfilment workflow.

        The workflow will:
        1. Validate the order
        2. Reserve inventory + initiate payment charge (parallel)
        3. Payment step SUSPENDS -- waiting for webhook at POST /webhooks/payment
        4. Once payment confirmed, ship the order (polls for tracking)
        5. Send confirmation email
        """
        store = get_store()
        workflow = get_workflow()

        order_id = f"ORD-{uuid.uuid4().hex[:8].upper()}"

        order_data = {
            "order_id": order_id,
            "customer_email": request.customer_email,
            "shipping_region": request.shipping_region,
            "items": [item.model_dump() for item in request.items],
            "created_at": datetime.now(UTC).isoformat(),
        }

        run = workflow.create_run()
        run.context = {"order": order_data}
        await store.save(run)

        logger.info(
            "\033[1mOrder %s created -- workflow run %s\033[0m",
            order_id,
            run.id,
        )

        return {
            "order_id": order_id,
            "run_id": str(run.id),
            "status": run.status.value,
            "message": "Order created. Workflow will begin processing shortly.",
        }

    @app.get("/orders/{run_id}")
    async def get_order_status(run_id: str) -> OrderStatusResponse:
        """
        Get the current state of an order's workflow.

        Shows each step's status, outputs, errors, and suspension details.
        """
        store = get_store()
        try:
            run = await store.load(run_id)
        except Exception as exc:
            raise HTTPException(status_code=404, detail=f"Run not found: {run_id}") from exc

        steps = [
            StepView(
                step_id=s.step_id,
                step_type=s.step_type,
                status=s.status.value,
                output=s.output,
                error=s.error,
                correlation_id=s.resume_correlation_id,
                next_poll_at=s.next_poll_at.isoformat() if s.next_poll_at else None,
            )
            for s in run.steps
        ]

        return OrderStatusResponse(
            run_id=str(run.id),
            workflow=run.workflow_name,
            version=run.workflow_version,
            status=run.status.value,
            steps=steps,
        )

    @app.post("/webhooks/payment")
    async def payment_webhook(payload: PaymentWebhookPayload) -> dict[str, str]:
        """
        Payment gateway webhook endpoint.

        The payment provider calls this URL with the result of a charge.
        The ``correlation_id`` matches the one generated by ChargePaymentStep,
        allowing the runner to find and resume the correct workflow.

        Example payload::

            {
                "correlation_id": "payment-ORD-A1B2C3D4-1711234567",
                "success": true,
                "charge_id": "ch_1234567890",
                "provider_ref": "pi_abc123",
            }
        """
        runner = get_runner()

        logger.info(
            "\033[1mPayment webhook received -- correlation_id: %s, success: %s\033[0m",
            payload.correlation_id,
            payload.success,
        )

        try:
            await runner.resume(
                correlation_id=payload.correlation_id,
                payload=payload.model_dump(exclude={"correlation_id"}),
            )
        except Exception as exc:
            logger.exception("Failed to resume workflow for correlation_id: %s", payload.correlation_id)
            raise HTTPException(status_code=400, detail=str(exc)) from exc

        # Give the runner a moment to pick up newly-ready steps
        await asyncio.sleep(0.5)

        return {
            "status": "accepted",
            "correlation_id": payload.correlation_id,
            "message": "Payment processed. Workflow resumed.",
        }

    @app.get("/health")
    async def health_check() -> dict[str, str]:
        """Health check endpoint."""
        runner = get_runner()
        store = get_store()
        return {
            "status": "healthy",
            "runner": "running" if runner and runner._running else "stopped",
            "store": type(store).__name__ if store else "not initialised",
        }
